<?php 
    require(ROUTE_DIR."lib/session.php"); 
    require(ROUTE_DIR."lib/autorisation.php");   
    require(ROUTE_DIR."lib/validator.php");
    require(ROUTE_DIR."lib/upload.php");  
    require(ROUTE_DIR."lib/database.php");
    require(ROUTE_DIR."modele/user.model.php");  
     require(ROUTE_DIR."modele/article.model.php");  
     require(ROUTE_DIR."modele/categorie.model.php");  
    require(ROUTE_DIR."modele/commentaire.model.php");  
?>